### PR TITLE
Shameless self promotion

### PR DESCRIPTION
**Pull request by jappeace**

### CODE REVIEW

**Comment by albohlabs** [comment]
Thank you very much for the PR but i only want to include articles which are working on basic knowledge on a specific topic. My aim is that when you have a specific questions you can pick a specific article from this list.

**Comment by jappeace** [comment]
I'm anwsering the question: "How to build a webserver in haskell" with little to no prior knowledge. I thought it was a pretty basic question.

**Comment by albohlabs** [comment]
You are right, it is a basic question. But when i talk about "basic knowledge" the focus is on the language itself. 
When it came to guiding on who to plug libs into each other, there is the _Three Layer Cake architecture pattern_ which is focusing on Servant + postgres and there is an example implementation [kowainik/issue-wanted](https://github.com/kowainik/issue-wanted).

**Comment by jappeace** [comment]
I think my series is quite a bit different from "Three Layer Cake architecture pattern". 
In that I assume little prior haskell experience, including knowledge of built systems, and I build out my example in stages:
1. first post for servant: https://github.com/jappeace/awesome-project-name/tree/simple-servent-setup
2. second post for side effects: https://github.com/jappeace/awesome-project-name/tree/message-servant
3. Third post does databases with beam: https://github.com/jappeace/awesome-project-name/tree/beam-postgres-db
4. Finally there is a reflex + servant one as well: https://github.com/jappeace/awesome-project-name/tree/reflex

My pasing is also a lot slower and I tried avoiding jargon. Besides I completely ignore achitecture because I believed it not to be important for small beginning web apps. Servant and reflex both already help a lot with that anyway.

**Pull request closed without merging**
